services:
  db:
    image: postgres:16
    container_name: qualidade-ar-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qualidade_ar
    ports:
      - "5434:5432"
    volumes:
      - qualidade-ar-db-data:/var/lib/postgresql/data

volumes:
  qualidade-ar-db-data:
