-- CreateTable
CREATE TABLE "QualidadeAr" (
    "id" SERIAL NOT NULL,
    "estacao" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL,
    "mp25" DOUBLE PRECISION NOT NULL,
    "co" DOUBLE PRECISION NOT NULL,
    "no3" DOUBLE PRECISION NOT NULL,
    "temperatura" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "QualidadeAr_pkey" PRIMARY KEY ("id")
);
