services:
  db:
    image: postgres:16
    container_name: transito-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transito
    ports:
      - "5435:5432"
    volumes:
      - transito-db-data:/var/lib/postgresql/data

volumes:
  transito-db-data:
